version: '3.5'

services:

  api-core:
    image: stock-listener:latest
    command: "script-core.sh"
    ports:
    - 8050:8050
    volumes:
    - ./api-core:/go/src/github.com/danielsussa/stock-listener/api-core
    - ./vendor:/go/src/github.com/danielsussa/stock-listener/vendor
    - ./api-core/assets:/build/assets 
    - ./scripts:/scripts
    network_mode: "host"

  api-mock:
    image: stock-listener:latest
    command: "script-mock.sh"
    volumes:
    - ./api-mock:/go/src/github.com/danielsussa/stock-listener/api-mock
    - ./vendor:/go/src/github.com/danielsussa/stock-listener/vendor
    - ./scripts:/scripts
    network_mode: "host"